# Generated by Django 4.0.1 on 2022-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.CharField(max_length=250),
        ),
    ]
