# Generated by Django 4.0.1 on 2022-01-20 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_msg_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 2, 52, 39, 118380)),
        ),
    ]
